---
- hosts: jenkins
  become: yes
  remote_user: ubuntu
  become_user: root
  become_method: sudo
  tasks:
    - name: 'apt get update'
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
    - name: 'Software Properties Common'
      become: true
      apt:
        name: software-properties-common
        state: present
    - name: 'Install Java Runtime Environment'
      apt:
        name: default-jre
        state: present
    - name: 'Add Jenkins Key'
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present
    - name: 'Add Jenkins Repository'
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        update_cache: yes
    - name: 'Install Jenkins'
      apt:
        name: jenkins
        update_cache: yes
        state: present
    - name: Enable Jenkins Service
      service:
        name: jenkins
        enabled: yes
    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
